Add support for run, runmod, and runzip vertx run options.

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -72,7 +72,7 @@ function stop() {
   fi
 }
 
-function replace_envs {
+function setup_hazelcast {
   # Need to copy the cluster.xml file everytime (seems to be the only way to get this to work)
   cp -r ${OPENSHIFT_VERTX_DIR}/versions/${OPENSHIFT_VERTX_VERSION}/dist/conf/cluster.xml $OPENSHIFT_VERTX_DIR/dist/conf
   
@@ -98,19 +98,45 @@ function replace_envs {
 }
 
 function start() {
-  replace_envs
-  
-  pushd ${OPENSHIFT_HOMEDIR}/app-root/repo
+  echo "Starting Vert.x cartridge"
 
-    if [ -z "$OPENSHIFT_VERTX_CLUSTER_PROXY_PORT" ]; then
-      $VERTX_HOME/bin/vertx run ./server.js >> $logf 2>&1 &
-    else
-      VERTX_OPTS="-Dhazelcast.local.localAddress=${OPENSHIFT_VERTX_IP} -Dhazelcast.socket.server.bind.any=false -Dhazelcast.socket.client.bind=false \
-                  -Dvertx.cluster.public.host=${OPENSHIFT_VERTX_PROXY_IP} -Dvertx.cluster.public.port=${OPENSHIFT_VERTX_VERTX_PROXY_PORT}"
-      export VERTX_OPTS
+  if isrunning; then
+      echo "Application is already running"
+      return 0
+  fi
 
-      $VERTX_HOME/bin/vertx run ./server.js -cluster -cluster-port $OPENSHIFT_VERTX_VERTX_PORT -cluster-host $OPENSHIFT_VERTX_IP >> $logf 2>&1 &
-    fi
+  envf="$OPENSHIFT_REPO_DIR/configuration/vertx.env"
+  #  Source environment if it exists.
+  [ -f "$envf" ]  &&  source "$envf"
+
+  # Determine correct vertx run command (run, runmod, runzip). TODO: A nice feature would have vertx have one run command
+  if [ "$vertx_zip" ]; then
+    vertx_run="runzip $vertx_zip"
+  fi
+  if [ "$vertx_module" ]; then
+    vertx_run="runmod $vertx_module"
+  fi
+  if [ "$vertx_app" ]; then
+    vertx_run="run $vertx_app"
+  fi
+
+  if [ -z "$vertx_run" ]; then
+    error "Could not determine how to run vertx. Make sure you have configured vertx_app|vertx_module|vertx_zip in $envf" 1>&2 1
+  fi
+
+  # Setup clustering
+  if [ "$OPENSHIFT_VERTX_CLUSTER_PROXY_PORT" ]; then
+    setup_hazelcast
+
+    VERTX_OPTS="$VERTX_OPTS -Dvertx.cluster.public.host=${OPENSHIFT_VERTX_PROXY_IP} -Dvertx.cluster.public.port=${OPENSHIFT_VERTX_VERTX_PROXY_PORT}"
+    export VERTX_OPTS
+
+    vertx_cluster = "-cluster -cluster-port $OPENSHIFT_VERTX_VERTX_PORT -cluster-host $OPENSHIFT_VERTX_IP"
+  fi
+
+  pushd $OPENSHIFT_REPO_DIR
+
+    $VERTX_HOME/bin/vertx $vertx_run $vertx_options $vertx_cluster >> $logf 2>&1 &
     
     PROCESS_ID=$!
     echo "$PROCESS_ID" > ${VERTX_PID_FILE}
