Trial and error

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -2,21 +2,26 @@
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
 
-vertx_BIN_DIR=${OPENSHIFT_VERTX_DIR}/bin
-vertx_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/vertx.pid
+case "$1" in
+  -v|--version)
+    version="$2"
+esac
+
+VERTX_HOME=${OPENSHIFT_VERTX_DIR}/vert.x
+VERTX_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/vertx.pid
+
+logf="$OPENSHIFT_VERTX_LOG_DIR/vertx.log"
 
 cartridge_type="vertx"
 
-VERTX_BIN_DIR=${OPENSHIFT_VERTX_DIR}/bin
-VERTX_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/vertx.pid
 
-# Check if the jbossas process is running
+# Check if the vertx process is running
 function isrunning() {
     
     # Check for running app
     if [ -f "$VERTX_PID_FILE" ]; then
-      jbpid=$(cat $VERTX_PID_FILE);
-      if /bin/ps --pid $jbpid 1>&2 >/dev/null;
+      vertxpid=$(cat $VERTX_PID_FILE);
+      if /bin/ps --pid $vertxpid 1>&2 >/dev/null;
       then
         return 0
       fi
@@ -64,20 +69,18 @@ function stop() {
   if isrunning; then
 		if [ -f "$VERTX_PID_FILE" ]; then
       pid=$(cat $VERTX_PID_FILE);
-      echo "Sending SIGTERM to jboss:$pid ..." 1>&2
+      echo "Sending SIGTERM to vertx:$pid ..." 1>&2
       killtree $pid
     else 
-	    echo "Failed to locate JBOSS PID File" 1>&2
+	    echo "Failed to locate Vert.x PID File" 1>&2
 	  fi
   fi
 }
 
 function replace_envs {
-    version=1.3
-    
-	cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/bin/run-vertx.sh $OPENSHIFT_VERTX_DIR/bin
-	cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/vert.x-1.3.1.final/conf/cluster.xml $OPENSHIFT_VERTX_DIR/vert.x-1.3.1.final/conf
-	cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/vert.x-1.3.1.final/bin/vertx $OPENSHIFT_VERTX_DIR/vert.x-1.3.1.final/bin
+	#cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/bin/run-vertx.sh $OPENSHIFT_VERTX_DIR/bin
+	#cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/vert.x-${version}/conf/cluster.xml $OPENSHIFT_VERTX_DIR/vert.x-${version}/conf
+	#cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/vert.x-${version}/bin/vertx $OPENSHIFT_VERTX_DIR/vert.x-${version}/bin
 	
 	if [ -z "$OPENSHIFT_VERTX_CLUSTER" ]; then
 		OPENSHIFT_VERTX_CLUSTER="${OPENSHIFT_VERTX_IP}"
@@ -91,31 +94,31 @@ function replace_envs {
 	done
 	
 	pushd $OPENSHIFT_VERTX_DIR
-		sed -i -e "s/\${env.OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/g" \
-				-e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
-				-e "s/\${env.OPENSHIFT_VERTX_CLUSTER}/${hostnames}/g" \
-				./vert.x-1.3.1.final/conf/cluster.xml
+		#sed -i -e "s/\${env.OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/g" \
+		#		-e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
+		#		-e "s/\${env.OPENSHIFT_VERTX_CLUSTER}/${hostnames}/g" \
+		#		./vert.x-${version}/conf/cluster.xml
 				
 		sed -i -e "s/\${env.OPENSHIFT_VERTX_IP}/${OPENSHIFT_VERTX_IP}/g" \
 				-e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
 				-e "s/\${env.OPENSHIFT_VERTX_VERTX_PROXY_PORT}/${OPENSHIFT_VERTX_VERTX_PROXY_PORT}/g" \
 				./bin/run-vertx.sh
 			
-		sed -i -e "s/\${env.OPENSHIFT_VERTX_IP}/${OPENSHIFT_VERTX_IP}/g" \
-			-e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
-			-e "s/\${env.OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/g" \
-			./vert.x-1.3.1.final/bin/vertx
+		#sed -i -e "s/\${env.OPENSHIFT_VERTX_IP}/${OPENSHIFT_VERTX_IP}/g" \
+		#	-e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
+		#	-e "s/\${env.OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/g" \
+		#	./vert.x-${version}/bin/vertx
 	popd
 }
 
 function start() {
-
-    replace_envs
-
-	pushd ${OPENSHIFT_VERTX_DIR}/template
-		../bin/run-vertx.sh > ${OPENSHIFT_TMP_DIR}/${cartridge_type}.log 2>&1 &
-		PROCESS_ID=$!
-    	echo "$PROCESS_ID" > ${VERTX_PID_FILE}
+  
+  #export VERTX_OPTS="-DOPENSHIFT_VERTX_IP=${OPENSHIFT_VERTX_IP} -DOPENSHIFT_VERTX_PORT=${OPENSHIFT_VERTX_PORT}"
+	
+  pushd ${OPENSHIFT_HOMEDIR}/app-root/repo
+    $VERTX_HOME/bin/vertx run ./server.js >> $logf 2>&1 &
+    PROCESS_ID=$!
+    echo "$PROCESS_ID" > ${VERTX_PID_FILE}
 	popd
 
 }
