Attempt clustering, remove 1.3 stuff

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -2,12 +2,7 @@
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
 
-case "$1" in
-  -v|--version)
-    version="$2"
-esac
-
-VERTX_HOME=${OPENSHIFT_VERTX_DIR}/vert.x
+VERTX_HOME=${OPENSHIFT_VERTX_DIR}/dist
 VERTX_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/vertx.pid
 
 logf="$OPENSHIFT_VERTX_LOG_DIR/vertx.log"
@@ -67,76 +62,69 @@ function stop() {
   echo "Stopping $cartridge_type cart"
   
   if isrunning; then
-		if [ -f "$VERTX_PID_FILE" ]; then
+    if [ -f "$VERTX_PID_FILE" ]; then
       pid=$(cat $VERTX_PID_FILE);
       echo "Sending SIGTERM to vertx:$pid ..." 1>&2
       killtree $pid
     else 
-	    echo "Failed to locate Vert.x PID File" 1>&2
-	  fi
+      echo "Failed to locate Vert.x PID File" 1>&2
+    fi
   fi
 }
 
 function replace_envs {
-	#cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/bin/run-vertx.sh $OPENSHIFT_VERTX_DIR/bin
-	#cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/vert.x-${version}/conf/cluster.xml $OPENSHIFT_VERTX_DIR/vert.x-${version}/conf
-	#cp -r ${OPENSHIFT_VERTX_DIR}/versions/${version}/vert.x-${version}/bin/vertx $OPENSHIFT_VERTX_DIR/vert.x-${version}/bin
-	
-	if [ -z "$OPENSHIFT_VERTX_CLUSTER" ]; then
-		OPENSHIFT_VERTX_CLUSTER="${OPENSHIFT_VERTX_IP}"
-	fi
-	
-	OPENSHIFT_VERTX_PROXY_IP=$(ping -c 1 ${OPENSHIFT_GEAR_DNS} | awk '{ print $3 ; exit }' | sed 's/(//g' | sed 's/)//g')
-	
-	hostnames=
-	for address in $OPENSHIFT_VERTX_CLUSTER; do
-		hostnames="<hostname>$address<\/hostname>${hostnames}"
-	done
-	
-	pushd $OPENSHIFT_VERTX_DIR
-		#sed -i -e "s/\${env.OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/g" \
-		#		-e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
-		#		-e "s/\${env.OPENSHIFT_VERTX_CLUSTER}/${hostnames}/g" \
-		#		./vert.x-${version}/conf/cluster.xml
-				
-		sed -i -e "s/\${env.OPENSHIFT_VERTX_IP}/${OPENSHIFT_VERTX_IP}/g" \
-				-e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
-				-e "s/\${env.OPENSHIFT_VERTX_VERTX_PROXY_PORT}/${OPENSHIFT_VERTX_VERTX_PROXY_PORT}/g" \
-				./bin/run-vertx.sh
-			
-		#sed -i -e "s/\${env.OPENSHIFT_VERTX_IP}/${OPENSHIFT_VERTX_IP}/g" \
-		#	-e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
-		#	-e "s/\${env.OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/g" \
-		#	./vert.x-${version}/bin/vertx
-	popd
+  # Need to copy the cluster.xml file everytime (seems to be the only way to get this to work)
+  cp -r ${OPENSHIFT_VERTX_DIR}/versions/${OPENSHIFT_VERTX_VERSION}/dist/conf/cluster.xml $OPENSHIFT_VERTX_DIR/dist/conf
+  
+  if [ -z "$OPENSHIFT_VERTX_CLUSTER" ]; then
+    OPENSHIFT_VERTX_CLUSTER="${OPENSHIFT_VERTX_IP}"
+  fi
+  
+  OPENSHIFT_VERTX_PROXY_IP=$(ping -c 1 ${OPENSHIFT_GEAR_DNS} | awk '{ print $3 ; exit }' | sed 's/(//g' | sed 's/)//g')
+  
+  hostnames=
+  for address in $OPENSHIFT_VERTX_CLUSTER; do
+    hostnames="<hostname>$address<\/hostname>${hostnames}"
+  done
+  
+  pushd $OPENSHIFT_VERTX_DIR
+      sed -i  -e "s/\${env.OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}/g" \
+              -e "s/\${env.OPENSHIFT_VERTX_CLUSTER_PORT}/${OPENSHIFT_VERTX_CLUSTER_PORT}/g" \
+              -e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
+              -e "s/\${env.OPENSHIFT_VERTX_IP}/${OPENSHIFT_VERTX_IP}/g" \
+              -e "s/\${env.OPENSHIFT_VERTX_CLUSTER}/${hostnames}/g" \
+              ./dist/conf/cluster.xml
+  popd
 }
 
 function start() {
+  replace_envs
   
-  #export VERTX_OPTS="-DOPENSHIFT_VERTX_IP=${OPENSHIFT_VERTX_IP} -DOPENSHIFT_VERTX_PORT=${OPENSHIFT_VERTX_PORT}"
-	
   pushd ${OPENSHIFT_HOMEDIR}/app-root/repo
-    $VERTX_HOME/bin/vertx run ./server.js >> $logf 2>&1 &
+
+    VERTX_OPTS="-Dhazelcast.local.localAddress=${OPENSHIFT_VERTX_IP} -Dhazelcast.socket.server.bind.any=false -Dhazelcast.socket.client.bind.any=false\
+                -Dvertx.cluster.public.host=${OPENSHIFT_VERTX_PROXY_IP} -Dvertx.cluster.public.port=${OPENSHIFT_VERTX_VERTX_PROXY_PORT}"
+    export VERTX_OPTS
+
+    $VERTX_HOME/bin/vertx run ./server.js -cluster -cluster-port $OPENSHIFT_VERTX_VERTX_PORT -cluster-host $OPENSHIFT_VERTX_IP >> $logf 2>&1 &
+    
     PROCESS_ID=$!
     echo "$PROCESS_ID" > ${VERTX_PID_FILE}
-	popd
+  popd
 
 }
 
 function restart() {
     echo "Restarting $cartridge_type cart"
    
-  	stop
-  	
-  	start
+    stop
+    
+    start
 }
 
 case "$1" in
   start)        start ;;
-  stop)			stop ;;
-  restart) 		restart ;;
+  stop)     stop ;;
+  restart)    restart ;;
   *)            exit 0
 esac
-
-
-
